// Curated structural events (connections layer) and fallback seeds served when live sources fail.

export const CHOKEPOINTS = [
  {id:'cp_hormuz',type:'connection',subtype:'chokepoint',title:'Strait of Hormuz — Oil Chokepoint',location:'Strait of Hormuz',lat:26.59,lng:56.25,severity:5,age:'Structural',brief:'~20% of global oil transit daily. Iran controls the northern shore. A closure would spike oil prices 40%+ within weeks and cascade into every conflict zone dependent on Gulf funding.',stats:[{label:'Daily Oil Transit',val:'~17M bbl/d'},{label:'Global Oil Share',val:'~20%'}],sources:[{n:'EIA',a:'2024'}],tags:['Energy','Iran','Saudi Arabia','Oil','Chokepoint']},
  {id:'cp_suez',type:'connection',subtype:'chokepoint',title:'Suez Canal — Asia-Europe Artery',location:'Suez Canal, Egypt',lat:30.46,lng:32.35,severity:5,age:'Structural',brief:'~12% of global trade by volume. Houthi attacks in the Red Sea since late 2023 forced most shipping to reroute via Cape of Good Hope — adding 10–14 days and $1M+ per voyage. Egypt Suez revenue down ~60%.',stats:[{label:'Global Trade Share',val:'~12%'},{label:'Egypt Revenue Loss',val:'~60%'}],sources:[{n:'Suez Canal Authority',a:'2024'},{n:'UNCTAD',a:'2024'}],tags:['Trade','Egypt','Red Sea','Houthi','Chokepoint','Yemen']},
  {id:'cp_malacca',type:'connection',subtype:'chokepoint',title:'Strait of Malacca — Asia Pacific Gateway',location:'Strait of Malacca',lat:2.5,lng:101.5,severity:4,age:'Structural',brief:'~40% of global trade passes through. China, Japan, and South Korea depend on it for ~80% of oil imports. Any blockage triggers immediate energy market panic across Asia.',stats:[{label:'Global Trade Share',val:'~40%'},{label:'Asian Oil Imports',val:'~80%'}],sources:[{n:'IMO',a:'2024'}],tags:['Trade','China','Japan','Energy','Chokepoint']},
  {id:'cp_panama',type:'connection',subtype:'chokepoint',title:'Panama Canal — Americas Route',location:'Panama Canal',lat:9.08,lng:-79.68,severity:4,age:'Structural',brief:'~5% of global trade. 2023–2024 drought reduced canal capacity by 40%, forcing rerouting. A structural vulnerability exposed by climate change, further complicated by US political pressure.',stats:[{label:'Global Trade Share',val:'~5%'},{label:'2024 Drought Impact',val:'-40% capacity'}],sources:[{n:'Panama Canal Authority',a:'2024'}],tags:['Trade','Panama','Americas','Climate','Chokepoint']},
  {id:'cp_bosphorus',type:'connection',subtype:'chokepoint',title:'Bosphorus Strait — Black Sea Gate',location:'Istanbul, Turkey',lat:41.11,lng:29.08,severity:3,age:'Structural',brief:'Only exit from the Black Sea to the Mediterranean. Turkey controls access under the Montreux Convention. Ukraine war made this a critical choke for grain exports and military logistics.',stats:[{label:'Grain Exports',val:'Ukraine / Russia'},{label:'Legal Control',val:'Turkey (Montreux)'}],sources:[{n:'IMO',a:'2024'}],tags:['Trade','Turkey','Ukraine','Russia','Grain','Chokepoint']},
  {id:'cp_babelmandeb',type:'connection',subtype:'chokepoint',title:'Bab-el-Mandeb — Red Sea Entry',location:'Djibouti',lat:12.58,lng:43.35,severity:5,age:'Structural',brief:'The gateway into the Red Sea and Suez Canal. Houthi attacks since late 2023 have diverted 80%+ of commercial shipping. Connects Yemen conflict directly to global trade disruption and Egypt\'s economic crisis.',stats:[{label:'Ships Diverted',val:'>80%'},{label:'Suez Revenue Hit',val:'-60%'}],sources:[{n:'UNCTAD',a:'2024'}],tags:['Yemen','Houthi','Trade','Red Sea','Egypt','Chokepoint']}
];
export const ECONOMIC_STRESS = [
  {id:'ec_argentina',type:'connection',subtype:'economic',title:'Argentina — Hyperinflation Crisis',location:'Argentina',lat:-38.42,lng:-63.62,severity:4,age:'Ongoing',brief:'Milei\'s shock therapy austerity. Inflation peaked at 211% in 2023, now declining with cuts. IMF $44B program. Peso devalued 50%+. A case study in whether fiscal brutalism stabilizes or implodes.',stats:[{label:'Peak Inflation',val:'211%'},{label:'IMF Program',val:'$44B'}],sources:[{n:'IMF',a:'2024'}],tags:['Argentina','Inflation','IMF','Economic Crisis']},
  {id:'ec_egypt',type:'connection',subtype:'economic',title:'Egypt — Currency & Suez Crisis',location:'Egypt',lat:26.82,lng:30.80,severity:4,age:'Ongoing',brief:'Lost $10B+ in annual Suez Canal revenue to Houthi-driven shipping diversions. Pound devalued 60%. Secured $50B IMF package. The Gaza war, Houthi attacks, and economic collapse are one interconnected story.',stats:[{label:'Suez Revenue Lost',val:'$10B+'},{label:'IMF Package',val:'$50B'}],sources:[{n:'IMF',a:'2024'}],tags:['Egypt','Suez','IMF','Currency','Economic Crisis','Gaza']},
  {id:'ec_pakistan',type:'connection',subtype:'economic',title:'Pakistan — IMF Lifeline',location:'Pakistan',lat:30.38,lng:69.35,severity:3,age:'Ongoing',brief:'$7B IMF bailout secured in 2024. Inflation >20%. Political instability post-Imran Khan arrest compounds economic fragility. Nuclear state on a debt treadmill.',stats:[{label:'IMF Bailout',val:'$7B'},{label:'Inflation',val:'>20%'}],sources:[{n:'IMF',a:'2024'}],tags:['Pakistan','IMF','Inflation','Economic Crisis']},
  {id:'ec_turkey',type:'connection',subtype:'economic',title:'Turkey — Post-Election Stabilization',location:'Turkey',lat:38.96,lng:35.24,severity:3,age:'Ongoing',brief:'Inflation peaked at 85% in 2022. Erdogan reversed unorthodox monetary policy after 2023 election. Lira down 80%+ since 2018. Controls Bosphorus, mediates between Russia and Ukraine — economic leverage deployed politically.',stats:[{label:'Lira Decline (5yr)',val:'-80%+'},{label:'Peak Inflation',val:'85%'}],sources:[{n:'CBRT',a:'2024'}],tags:['Turkey','Lira','Inflation','Economic Crisis','Bosphorus']}
];
export const POLITICAL_FLASH = [
  {id:'pf_taiwan',type:'connection',subtype:'political',title:'Taiwan — Cross-Strait Flashpoint',location:'Taiwan',lat:23.7,lng:120.96,severity:5,age:'Structural',brief:'Lai Ching-te (pro-independence) won January 2024 election. China responded with military exercises. US "strategic ambiguity" under strain. Control of Taiwan Strait = control of global semiconductor supply.',stats:[{label:'PRC Response',val:'Military exercises'},{label:'Semiconductor Share',val:'>60% advanced chips'}],sources:[{n:'Reuters',a:'2024'}],tags:['Taiwan','China','USA','Military','Semiconductor','Political','Chokepoint']},
  {id:'pf_iran',type:'connection',subtype:'political',title:'Iran — Post-Raisi Nuclear Posture',location:'Iran',lat:32.43,lng:53.69,severity:4,age:'Ongoing',brief:'Raisi died in helicopter crash May 2024. Reformist Pezeshkian won snap election. Nuclear enrichment at 60%+. Proxy network (Hezbollah, Houthi, Hamas, PMF) active across 5 countries — Iran as thread connecting multiple conflict dots.',stats:[{label:'Uranium Enrichment',val:'60%+ (U-235)'},{label:'Active Proxies',val:'5 countries'}],sources:[{n:'IAEA',a:'2024'}],tags:['Iran','Nuclear','Hezbollah','Houthi','Hamas','Middle East','Political']},
  {id:'pf_sahel',type:'connection',subtype:'political',title:'Sahel — The Coup Belt',location:'Mali',lat:17.57,lng:-3.99,severity:4,age:'Structural',brief:'Mali, Burkina Faso, and Niger all fell to military coups (2020–2023). Formed the Alliance of Sahel States, expelled French forces, invited Wagner/Russia. A template for anti-Western realignment spreading south.',stats:[{label:'Coups (2020-23)',val:'3 countries'},{label:'French Forces',val:'Expelled'}],sources:[{n:'ECOWAS',a:'2024'}],tags:['Mali','Niger','Burkina Faso','Coup','Russia','Wagner','Sahel','Political']},
  {id:'pf_venezuela',type:'connection',subtype:'political',title:'Venezuela — Stolen Election',location:'Venezuela',lat:6.42,lng:-66.59,severity:4,age:'Ongoing',brief:'Maduro claimed 2024 election victory. Carter Center and most international observers rejected results. Edmundo González fled to Spain. Ongoing arrests of opposition. Migration crisis — 7M+ Venezuelans abroad — is the region\'s largest displacement.',stats:[{label:'Venezuelans Abroad',val:'7M+'},  {label:'Int\'l Recognition',val:'Widely disputed'}],sources:[{n:'Carter Center',a:'2024'}],tags:['Venezuela','Maduro','Election','Migration','Political']}
];

export const SEEDS = {
  conflict:[
    {id:'sc1',type:'conflict',title:'Gaza: Aid Corridor Negotiations Stall',location:'Gaza Strip',lat:31.35,lng:34.31,severity:5,age:'30m ago',brief:'Ceasefire negotiations have stalled. 340+ aid trucks blocked from entering northern Gaza over 72 hours.',stats:[{label:'Displaced',val:'1.7M'},{label:'Aid Blocked',val:'72h+'}],sources:[{n:'UN OCHA',a:'1h'},{n:'Al Jazeera',a:'30m'}],tags:['Gaza','Palestine','Israel']},
    {id:'sc2',type:'conflict',title:'Ukraine: Kharkiv Shelling Intensifies',location:'Kharkiv, Ukraine',lat:49.99,lng:36.23,severity:5,age:'45m ago',brief:'Russian forces intensified strikes on Kharkiv Oblast. Ukrainian air defense intercepted 8 of 11 overnight drones.',stats:[{label:'Strikes (24h)',val:'14'},{label:'Intercepted',val:'8/11'}],sources:[{n:'Reuters',a:'45m'},{n:'Kyiv Post',a:'1h'}],tags:['Ukraine','Russia','War']},
    {id:'sc3',type:'conflict',title:'Sudan: RSF Advances on El Fasher',location:'El Fasher, Sudan',lat:13.63,lng:25.35,severity:4,age:'3h ago',brief:'RSF forces control two more districts surrounding El Fasher, with ~800,000 civilians sheltering in the city.',stats:[{label:'Civilians',val:'~800K'},{label:'Risk',val:'CRITICAL'}],sources:[{n:'UN OCHA',a:'3h'}],tags:['Sudan','Darfur','RSF']}
  ],
  humanitarian:[
    {id:'sh1',type:'humanitarian',title:'Yemen: Famine in 4 Governorates',location:'Yemen',lat:15.55,lng:48.52,severity:5,age:'1d ago',brief:'WFP classified four Yemeni governorates IPC Phase 5. 2.7M face catastrophic food insecurity.',stats:[{label:'At Risk',val:'2.7M'},{label:'Ration Cut',val:'50%'}],sources:[{n:'WFP',a:'1d'}],tags:['Yemen','Famine','WFP']},
    {id:'sh2',type:'humanitarian',title:'Haiti: Gang Violence Blocks Aid',location:'Port-au-Prince, Haiti',lat:18.54,lng:-72.34,severity:4,age:'6h ago',brief:'Gang violence blocked humanitarian aid corridors for the 5th consecutive day. 580,000 displaced.',stats:[{label:'Displaced',val:'580K'}],sources:[{n:'UN OCHA',a:'6h'}],tags:['Haiti','Displacement']}
  ]
};

export const FALLBACK_LAUNCHES = [
  {id:'fl0',type:'launch',title:'SpaceX Falcon 9 — Starlink',location:'Cape Canaveral, FL',lat:28.61,lng:-80.6,severity:2,age:'In 2 days',brief:'SpaceX Falcon 9 carrying Starlink v2 Mini satellites from SLC-40.',sources:[{n:'SpaceX',a:'Upcoming'}],tags:['SpaceX','Starlink']},
  {id:'fl1',type:'launch',title:'Rocket Lab Electron — Commercial',location:'Mahia, New Zealand',lat:-39.26,lng:177.86,severity:2,age:'In 5 days',brief:'Rocket Lab Electron launching commercial payload from Mahia Peninsula.',sources:[{n:'Rocket Lab',a:'Upcoming'}],tags:['Rocket Lab','Electron']}
];
